name: TimeSenseCompanion
options:
  bundleIdPrefix: com.timesense
  deploymentTarget:
    iOS: "16.0"
targets:
  TimeSenseCompanion:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - project.yml
          - README.md
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.timesense.companion
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

